# -*- coding: utf-8 -*-

################################################################################
## Form generated from reading UI file 'app.ui'
##
## Created by: Qt User Interface Compiler version 6.5.0
##
## WARNING! All changes made in this file will be lost when recompiling UI file!
################################################################################

from PySide6.QtCore import (QCoreApplication, QDate, QDateTime, QLocale,
    QMetaObject, QObject, QPoint, QRect,
    QSize, QTime, QUrl, Qt)
from PySide6.QtGui import (QBrush, QColor, QConicalGradient, QCursor,
    QFont, QFontDatabase, QGradient, QIcon,
    QImage, QKeySequence, QLinearGradient, QPainter,
    QPalette, QPixmap, QRadialGradient, QTransform)
from PySide6.QtWidgets import (QAbstractScrollArea, QApplication, QLabel, QListWidget,
    QListWidgetItem, QMainWindow, QPushButton, QScrollArea,
    QSizePolicy, QTabWidget, QTextBrowser, QTextEdit,
    QWidget)
import res_rc

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        if not MainWindow.objectName():
            MainWindow.setObjectName(u"MainWindow")
        MainWindow.resize(550, 440)
        icon = QIcon()
        icon.addFile(u":/icons/Icons/chat.png", QSize(), QIcon.Normal, QIcon.Off)
        MainWindow.setWindowIcon(icon)
        MainWindow.setStyleSheet(u"background-color: #483D8B;\n"
"color: #FFFFFF")
        MainWindow.setTabShape(QTabWidget.Rounded)
        self.centralwidget = QWidget(MainWindow)
        self.centralwidget.setObjectName(u"centralwidget")
        self.chat_viewer = QTextBrowser(self.centralwidget)
        self.chat_viewer.setObjectName(u"chat_viewer")
        self.chat_viewer.setGeometry(QRect(10, 60, 531, 301))
        font = QFont()
        font.setFamilies([u"Roboto Mono"])
        font.setPointSize(10)
        self.chat_viewer.setFont(font)
        self.chat_viewer.viewport().setProperty("cursor", QCursor(Qt.PointingHandCursor))
        self.chat_viewer.setFocusPolicy(Qt.NoFocus)
        self.chat_viewer.setLayoutDirection(Qt.LeftToRight)
        self.chat_viewer.setStyleSheet(u"border-radius: 8px;\n"
"border: 1px solid #e0e4e7;\n"
"padding: 5px 15px;\n"
"color: #FFFFFF;\n"
"background-color: #6A5ACD")
        self.chat_viewer.setVerticalScrollBarPolicy(Qt.ScrollBarAsNeeded)
        self.chat_input = QTextEdit(self.centralwidget)
        self.chat_input.setObjectName(u"chat_input")
        self.chat_input.setGeometry(QRect(10, 380, 321, 41))
        self.chat_input.setFont(font)
        self.chat_input.viewport().setProperty("cursor", QCursor(Qt.IBeamCursor))
        self.chat_input.setLayoutDirection(Qt.LeftToRight)
        self.chat_input.setStyleSheet(u"border-radius: 8px;\n"
"border: 1px solid #e0e4e7;\n"
"padding-right: 100px;\n"
"padding: 5px 15px;\n"
"color: #FFFFFF")
        self.chat_input.setSizeAdjustPolicy(QAbstractScrollArea.AdjustIgnored)
        self.send_button = QPushButton(self.centralwidget)
        self.send_button.setObjectName(u"send_button")
        self.send_button.setGeometry(QRect(340, 380, 61, 41))
        self.send_button.setStyleSheet(u"border-radius: 8px;\n"
"border: 1px solid #e0e4e7;\n"
"padding: 5px 15px;\n"
"color: #FFFFFF;\n"
"background-color: #7B68EE;")
        icon1 = QIcon()
        icon1.addFile(u":/icons/Icons/send (1).png", QSize(), QIcon.Normal, QIcon.Off)
        self.send_button.setIcon(icon1)
        self.send_button.setIconSize(QSize(30, 30))
        self.emoji_area = QScrollArea(self.centralwidget)
        self.emoji_area.setObjectName(u"emoji_area")
        self.emoji_area.setGeometry(QRect(250, 140, 291, 231))
        self.emoji_area.setFocusPolicy(Qt.NoFocus)
        self.emoji_area.setContextMenuPolicy(Qt.NoContextMenu)
        self.emoji_area.setStyleSheet(u"border-radius: 8px;\n"
"border: 1px solid #e0e4e7;\n"
"\n"
"color: #FFFFFF")
        self.emoji_area.setVerticalScrollBarPolicy(Qt.ScrollBarAsNeeded)
        self.emoji_area.setHorizontalScrollBarPolicy(Qt.ScrollBarAsNeeded)
        self.emoji_area.setWidgetResizable(False)
        self.scrollAreaWidgetContents = QWidget()
        self.scrollAreaWidgetContents.setObjectName(u"scrollAreaWidgetContents")
        self.scrollAreaWidgetContents.setGeometry(QRect(0, 0, 289, 229))
        self.emoji_1 = QPushButton(self.scrollAreaWidgetContents)
        self.emoji_1.setObjectName(u"emoji_1")
        self.emoji_1.setGeometry(QRect(10, 50, 31, 31))
        self.emoji_close_button = QPushButton(self.scrollAreaWidgetContents)
        self.emoji_close_button.setObjectName(u"emoji_close_button")
        self.emoji_close_button.setGeometry(QRect(250, 10, 31, 31))
        self.emoji_close_button.setStyleSheet(u"border-radius: 8px;\n"
"border: 1px solid #e0e4e7;\n"
"color: #FFFFFF;\n"
"background-color: #B22222;")
        self.emoji_2 = QPushButton(self.scrollAreaWidgetContents)
        self.emoji_2.setObjectName(u"emoji_2")
        self.emoji_2.setGeometry(QRect(40, 50, 31, 31))
        self.emoji_3 = QPushButton(self.scrollAreaWidgetContents)
        self.emoji_3.setObjectName(u"emoji_3")
        self.emoji_3.setGeometry(QRect(70, 50, 31, 31))
        self.emoji_4 = QPushButton(self.scrollAreaWidgetContents)
        self.emoji_4.setObjectName(u"emoji_4")
        self.emoji_4.setGeometry(QRect(100, 50, 31, 31))
        self.emoji_5 = QPushButton(self.scrollAreaWidgetContents)
        self.emoji_5.setObjectName(u"emoji_5")
        self.emoji_5.setGeometry(QRect(130, 50, 31, 31))
        self.emoji_6 = QPushButton(self.scrollAreaWidgetContents)
        self.emoji_6.setObjectName(u"emoji_6")
        self.emoji_6.setGeometry(QRect(160, 50, 31, 31))
        self.emoji_7 = QPushButton(self.scrollAreaWidgetContents)
        self.emoji_7.setObjectName(u"emoji_7")
        self.emoji_7.setGeometry(QRect(190, 50, 31, 31))
        self.emoji_8 = QPushButton(self.scrollAreaWidgetContents)
        self.emoji_8.setObjectName(u"emoji_8")
        self.emoji_8.setGeometry(QRect(220, 50, 31, 31))
        self.emoji_9 = QPushButton(self.scrollAreaWidgetContents)
        self.emoji_9.setObjectName(u"emoji_9")
        self.emoji_9.setGeometry(QRect(250, 50, 31, 31))
        self.emoji_14 = QPushButton(self.scrollAreaWidgetContents)
        self.emoji_14.setObjectName(u"emoji_14")
        self.emoji_14.setGeometry(QRect(130, 80, 31, 31))
        self.emoji_10 = QPushButton(self.scrollAreaWidgetContents)
        self.emoji_10.setObjectName(u"emoji_10")
        self.emoji_10.setGeometry(QRect(10, 80, 31, 31))
        self.emoji_17 = QPushButton(self.scrollAreaWidgetContents)
        self.emoji_17.setObjectName(u"emoji_17")
        self.emoji_17.setGeometry(QRect(220, 80, 31, 31))
        self.emoji_13 = QPushButton(self.scrollAreaWidgetContents)
        self.emoji_13.setObjectName(u"emoji_13")
        self.emoji_13.setGeometry(QRect(100, 80, 31, 31))
        self.emoji_18 = QPushButton(self.scrollAreaWidgetContents)
        self.emoji_18.setObjectName(u"emoji_18")
        self.emoji_18.setGeometry(QRect(250, 80, 31, 31))
        self.emoji_11 = QPushButton(self.scrollAreaWidgetContents)
        self.emoji_11.setObjectName(u"emoji_11")
        self.emoji_11.setGeometry(QRect(40, 80, 31, 31))
        self.emoji_15 = QPushButton(self.scrollAreaWidgetContents)
        self.emoji_15.setObjectName(u"emoji_15")
        self.emoji_15.setGeometry(QRect(160, 80, 31, 31))
        self.emoji_12 = QPushButton(self.scrollAreaWidgetContents)
        self.emoji_12.setObjectName(u"emoji_12")
        self.emoji_12.setGeometry(QRect(70, 80, 31, 31))
        self.emoji_16 = QPushButton(self.scrollAreaWidgetContents)
        self.emoji_16.setObjectName(u"emoji_16")
        self.emoji_16.setGeometry(QRect(190, 80, 31, 31))
        self.emoji_23 = QPushButton(self.scrollAreaWidgetContents)
        self.emoji_23.setObjectName(u"emoji_23")
        self.emoji_23.setGeometry(QRect(130, 110, 31, 31))
        self.emoji_19 = QPushButton(self.scrollAreaWidgetContents)
        self.emoji_19.setObjectName(u"emoji_19")
        self.emoji_19.setGeometry(QRect(10, 110, 31, 31))
        self.emoji_26 = QPushButton(self.scrollAreaWidgetContents)
        self.emoji_26.setObjectName(u"emoji_26")
        self.emoji_26.setGeometry(QRect(220, 110, 31, 31))
        self.emoji_22 = QPushButton(self.scrollAreaWidgetContents)
        self.emoji_22.setObjectName(u"emoji_22")
        self.emoji_22.setGeometry(QRect(100, 110, 31, 31))
        self.emoji_27 = QPushButton(self.scrollAreaWidgetContents)
        self.emoji_27.setObjectName(u"emoji_27")
        self.emoji_27.setGeometry(QRect(250, 110, 31, 31))
        self.emoji_20 = QPushButton(self.scrollAreaWidgetContents)
        self.emoji_20.setObjectName(u"emoji_20")
        self.emoji_20.setGeometry(QRect(40, 110, 31, 31))
        self.emoji_24 = QPushButton(self.scrollAreaWidgetContents)
        self.emoji_24.setObjectName(u"emoji_24")
        self.emoji_24.setGeometry(QRect(160, 110, 31, 31))
        self.emoji_21 = QPushButton(self.scrollAreaWidgetContents)
        self.emoji_21.setObjectName(u"emoji_21")
        self.emoji_21.setGeometry(QRect(70, 110, 31, 31))
        self.emoji_25 = QPushButton(self.scrollAreaWidgetContents)
        self.emoji_25.setObjectName(u"emoji_25")
        self.emoji_25.setGeometry(QRect(190, 110, 31, 31))
        self.emoji_32 = QPushButton(self.scrollAreaWidgetContents)
        self.emoji_32.setObjectName(u"emoji_32")
        self.emoji_32.setGeometry(QRect(130, 140, 31, 31))
        self.emoji_28 = QPushButton(self.scrollAreaWidgetContents)
        self.emoji_28.setObjectName(u"emoji_28")
        self.emoji_28.setGeometry(QRect(10, 140, 31, 31))
        self.emoji_35 = QPushButton(self.scrollAreaWidgetContents)
        self.emoji_35.setObjectName(u"emoji_35")
        self.emoji_35.setGeometry(QRect(220, 140, 31, 31))
        self.emoji_31 = QPushButton(self.scrollAreaWidgetContents)
        self.emoji_31.setObjectName(u"emoji_31")
        self.emoji_31.setGeometry(QRect(100, 140, 31, 31))
        self.emoji_36 = QPushButton(self.scrollAreaWidgetContents)
        self.emoji_36.setObjectName(u"emoji_36")
        self.emoji_36.setGeometry(QRect(250, 140, 31, 31))
        self.emoji_29 = QPushButton(self.scrollAreaWidgetContents)
        self.emoji_29.setObjectName(u"emoji_29")
        self.emoji_29.setGeometry(QRect(40, 140, 31, 31))
        self.emoji_33 = QPushButton(self.scrollAreaWidgetContents)
        self.emoji_33.setObjectName(u"emoji_33")
        self.emoji_33.setGeometry(QRect(160, 140, 31, 31))
        self.emoji_30 = QPushButton(self.scrollAreaWidgetContents)
        self.emoji_30.setObjectName(u"emoji_30")
        self.emoji_30.setGeometry(QRect(70, 140, 31, 31))
        self.emoji_34 = QPushButton(self.scrollAreaWidgetContents)
        self.emoji_34.setObjectName(u"emoji_34")
        self.emoji_34.setGeometry(QRect(190, 140, 31, 31))
        self.emoji_41 = QPushButton(self.scrollAreaWidgetContents)
        self.emoji_41.setObjectName(u"emoji_41")
        self.emoji_41.setGeometry(QRect(130, 170, 31, 31))
        self.emoji_37 = QPushButton(self.scrollAreaWidgetContents)
        self.emoji_37.setObjectName(u"emoji_37")
        self.emoji_37.setGeometry(QRect(10, 170, 31, 31))
        self.emoji_44 = QPushButton(self.scrollAreaWidgetContents)
        self.emoji_44.setObjectName(u"emoji_44")
        self.emoji_44.setGeometry(QRect(220, 170, 31, 31))
        self.emoji_40 = QPushButton(self.scrollAreaWidgetContents)
        self.emoji_40.setObjectName(u"emoji_40")
        self.emoji_40.setGeometry(QRect(100, 170, 31, 31))
        self.emoji_45 = QPushButton(self.scrollAreaWidgetContents)
        self.emoji_45.setObjectName(u"emoji_45")
        self.emoji_45.setGeometry(QRect(250, 170, 31, 31))
        self.emoji_38 = QPushButton(self.scrollAreaWidgetContents)
        self.emoji_38.setObjectName(u"emoji_38")
        self.emoji_38.setGeometry(QRect(40, 170, 31, 31))
        self.emoji_42 = QPushButton(self.scrollAreaWidgetContents)
        self.emoji_42.setObjectName(u"emoji_42")
        self.emoji_42.setGeometry(QRect(160, 170, 31, 31))
        self.emoji_39 = QPushButton(self.scrollAreaWidgetContents)
        self.emoji_39.setObjectName(u"emoji_39")
        self.emoji_39.setGeometry(QRect(70, 170, 31, 31))
        self.emoji_43 = QPushButton(self.scrollAreaWidgetContents)
        self.emoji_43.setObjectName(u"emoji_43")
        self.emoji_43.setGeometry(QRect(190, 170, 31, 31))
        self.base_icon = QLabel(self.scrollAreaWidgetContents)
        self.base_icon.setObjectName(u"base_icon")
        self.base_icon.setGeometry(QRect(200, 10, 41, 41))
        self.base_icon.setStyleSheet(u"background-color: transparent;\n"
"border: 0px;")
        self.base_icon.setPixmap(QPixmap(u":/icons/Icons/space-station.png"))
        self.base_icon.setScaledContents(True)
        self.scope_icon = QLabel(self.scrollAreaWidgetContents)
        self.scope_icon.setObjectName(u"scope_icon")
        self.scope_icon.setGeometry(QRect(20, 200, 31, 31))
        self.scope_icon.setStyleSheet(u"background-color: transparent;\n"
"border: 0px;")
        self.scope_icon.setPixmap(QPixmap(u":/icons/Icons/telescope.png"))
        self.scope_icon.setScaledContents(True)
        self.emoji_area.setWidget(self.scrollAreaWidgetContents)
        self.emoji_open_button = QPushButton(self.centralwidget)
        self.emoji_open_button.setObjectName(u"emoji_open_button")
        self.emoji_open_button.setGeometry(QRect(480, 380, 61, 41))
        self.emoji_open_button.setStyleSheet(u"border-radius: 8px;\n"
"border: 1px solid #e0e4e7;\n"
"padding: 5px 15px;\n"
"color: #FFFFFF;\n"
"background-color: #7B68EE;")
        icon2 = QIcon()
        icon2.addFile(u":/icons/Icons/love.png", QSize(), QIcon.Normal, QIcon.Off)
        self.emoji_open_button.setIcon(icon2)
        self.emoji_open_button.setIconSize(QSize(30, 30))
        self.menu_area = QScrollArea(self.centralwidget)
        self.menu_area.setObjectName(u"menu_area")
        self.menu_area.setGeometry(QRect(0, 0, 111, 440))
        self.menu_area.setStyleSheet(u"border-radius: 8px;\n"
"border-right: 1px solid #e0e4e7;\n"
"color: #FFFFFF")
        self.menu_area.setWidgetResizable(True)
        self.scrollAreaWidgetContents_2 = QWidget()
        self.scrollAreaWidgetContents_2.setObjectName(u"scrollAreaWidgetContents_2")
        self.scrollAreaWidgetContents_2.setGeometry(QRect(0, 0, 109, 438))
        self.menu_close_button = QPushButton(self.scrollAreaWidgetContents_2)
        self.menu_close_button.setObjectName(u"menu_close_button")
        self.menu_close_button.setGeometry(QRect(10, 10, 91, 41))
        self.menu_close_button.setFont(font)
        self.menu_close_button.setStyleSheet(u"border-radius: 8px;\n"
"border: 1px solid #e0e4e7;\n"
"color: #FFFFFF;\n"
"background-color: #7B68EE;")
        icon3 = QIcon()
        icon3.addFile(u":/icons/Icons/mercury.png", QSize(), QIcon.Normal, QIcon.Off)
        self.menu_close_button.setIcon(icon3)
        self.menu_close_button.setIconSize(QSize(40, 40))
        self.online_clients_open_button = QPushButton(self.scrollAreaWidgetContents_2)
        self.online_clients_open_button.setObjectName(u"online_clients_open_button")
        self.online_clients_open_button.setGeometry(QRect(10, 70, 91, 31))
        self.online_clients_open_button.setFont(font)
        self.online_clients_open_button.setStyleSheet(u"border-radius: 8px;\n"
"border: 1px solid #e0e4e7;\n"
"padding: 5px 15px;\n"
"color: #FFFFFF;\n"
"background-color: #7B68EE;")
        icon4 = QIcon()
        icon4.addFile(u":/icons/Icons/alien.png", QSize(), QIcon.Normal, QIcon.Off)
        self.online_clients_open_button.setIcon(icon4)
        self.online_clients_open_button.setIconSize(QSize(20, 20))
        self.label = QLabel(self.scrollAreaWidgetContents_2)
        self.label.setObjectName(u"label")
        self.label.setGeometry(QRect(10, 340, 91, 91))
        self.label.setStyleSheet(u"background-color: transparent;\n"
"border-right: 0px;")
        self.label.setPixmap(QPixmap(u":/icons/Icons/astronaut.png"))
        self.label.setScaledContents(True)
        self.label_6 = QLabel(self.scrollAreaWidgetContents_2)
        self.label_6.setObjectName(u"label_6")
        self.label_6.setGeometry(QRect(-40, 420, 191, 31))
        self.label_6.setStyleSheet(u"background-color: transparent;\n"
"border-right: 0px;")
        self.label_6.setPixmap(QPixmap(u":/icons/Icons/neptune.png"))
        self.label_6.setScaledContents(True)
        self.label_7 = QLabel(self.scrollAreaWidgetContents_2)
        self.label_7.setObjectName(u"label_7")
        self.label_7.setGeometry(QRect(10, 310, 41, 41))
        self.label_7.setStyleSheet(u"background-color: transparent;\n"
"border-right: 0px;")
        self.label_7.setPixmap(QPixmap(u":/icons/Icons/planet.png"))
        self.label_7.setScaledContents(True)
        self.label_8 = QLabel(self.scrollAreaWidgetContents_2)
        self.label_8.setObjectName(u"label_8")
        self.label_8.setGeometry(QRect(60, 330, 41, 41))
        self.label_8.setStyleSheet(u"background-color: transparent;\n"
"border-right: 0px;")
        self.label_8.setPixmap(QPixmap(u":/icons/Icons/orbit.png"))
        self.label_8.setScaledContents(True)
        self.label_10 = QLabel(self.scrollAreaWidgetContents_2)
        self.label_10.setObjectName(u"label_10")
        self.label_10.setGeometry(QRect(50, 280, 41, 41))
        self.label_10.setStyleSheet(u"background-color: transparent;\n"
"border-right: 0px;")
        self.label_10.setPixmap(QPixmap(u":/icons/Icons/planet (1).png"))
        self.label_10.setScaledContents(True)
        self.label_11 = QLabel(self.scrollAreaWidgetContents_2)
        self.label_11.setObjectName(u"label_11")
        self.label_11.setGeometry(QRect(10, 250, 41, 41))
        self.label_11.setStyleSheet(u"background-color: transparent;\n"
"border-right: 0px;")
        self.label_11.setPixmap(QPixmap(u":/icons/Icons/galaxy.png"))
        self.label_11.setScaledContents(True)
        self.label_12 = QLabel(self.scrollAreaWidgetContents_2)
        self.label_12.setObjectName(u"label_12")
        self.label_12.setGeometry(QRect(40, 240, 41, 41))
        self.label_12.setStyleSheet(u"background-color: transparent;\n"
"border-right: 0px;")
        self.label_12.setPixmap(QPixmap(u":/icons/Icons/satellite.png"))
        self.label_12.setScaledContents(True)
        self.menu_area.setWidget(self.scrollAreaWidgetContents_2)
        self.label_8.raise_()
        self.menu_close_button.raise_()
        self.online_clients_open_button.raise_()
        self.label_6.raise_()
        self.label.raise_()
        self.label_7.raise_()
        self.label_10.raise_()
        self.label_11.raise_()
        self.label_12.raise_()
        self.menu_open_button = QPushButton(self.centralwidget)
        self.menu_open_button.setObjectName(u"menu_open_button")
        self.menu_open_button.setGeometry(QRect(10, 10, 91, 41))
        self.menu_open_button.setFont(font)
        self.menu_open_button.setCursor(QCursor(Qt.ArrowCursor))
        self.menu_open_button.setStyleSheet(u"border-radius: 8px;\n"
"border: 1px solid #e0e4e7;\n"
"color: #FFFFFF;\n"
"background-color: #7B68EE;")
        icon5 = QIcon()
        icon5.addFile(u":/icons/Icons/earth.png", QSize(), QIcon.Normal, QIcon.Off)
        self.menu_open_button.setIcon(icon5)
        self.menu_open_button.setIconSize(QSize(40, 40))
        self.online_clients_area = QScrollArea(self.centralwidget)
        self.online_clients_area.setObjectName(u"online_clients_area")
        self.online_clients_area.setGeometry(QRect(110, 60, 145, 261))
        self.online_clients_area.setStyleSheet(u"border-radius: 8px;\n"
"border-right: 1px solid #e0e4e7;\n"
"border-top: 1px solid #e0e4e7;\n"
"border-bottom: 1px solid #e0e4e7;\n"
"color: #FFFFFF")
        self.online_clients_area.setWidgetResizable(True)
        self.scrollAreaWidgetContents_3 = QWidget()
        self.scrollAreaWidgetContents_3.setObjectName(u"scrollAreaWidgetContents_3")
        self.scrollAreaWidgetContents_3.setGeometry(QRect(0, 0, 143, 259))
        self.online_clients_label = QLabel(self.scrollAreaWidgetContents_3)
        self.online_clients_label.setObjectName(u"online_clients_label")
        self.online_clients_label.setGeometry(QRect(10, 10, 81, 31))
        font1 = QFont()
        font1.setFamilies([u"Roboto Mono"])
        font1.setPointSize(14)
        font1.setBold(False)
        font1.setUnderline(False)
        self.online_clients_label.setFont(font1)
        self.online_clients_label.setStyleSheet(u"border: 1px solid #e0e4e7;")
        self.online_clients_label.setTextFormat(Qt.PlainText)
        self.online_clients_label.setScaledContents(False)
        self.online_clients_close_button = QPushButton(self.scrollAreaWidgetContents_3)
        self.online_clients_close_button.setObjectName(u"online_clients_close_button")
        self.online_clients_close_button.setGeometry(QRect(100, 10, 31, 31))
        self.online_clients_close_button.setStyleSheet(u"border-radius: 8px;\n"
"border: 1px solid #e0e4e7;\n"
"color: #FFFFFF;\n"
"background-color: #B22222;")
        self.online_clients_list = QListWidget(self.scrollAreaWidgetContents_3)
        self.online_clients_list.setObjectName(u"online_clients_list")
        self.online_clients_list.setGeometry(QRect(10, 51, 121, 191))
        self.online_clients_list.setFont(font)
        self.online_clients_list.setStyleSheet(u"border-radius: 8px;\n"
"border: 1px solid #e0e4e7;\n"
"padding: 5px 5px;\n"
"color: #FFFFFF;\n"
"background-color: #6A5ACD")
        self.label_14 = QLabel(self.scrollAreaWidgetContents_3)
        self.label_14.setObjectName(u"label_14")
        self.label_14.setGeometry(QRect(0, 210, 51, 51))
        self.label_14.setStyleSheet(u"background-color: transparent;\n"
"border: 0px;")
        self.label_14.setPixmap(QPixmap(u":/icons/Icons/satelite.png"))
        self.label_14.setScaledContents(True)
        self.label_15 = QLabel(self.scrollAreaWidgetContents_3)
        self.label_15.setObjectName(u"label_15")
        self.label_15.setGeometry(QRect(90, -20, 71, 71))
        self.label_15.setStyleSheet(u"background-color: transparent;\n"
"border: 0px;")
        self.label_15.setPixmap(QPixmap(u":/icons/Icons/black-hole (1).png"))
        self.label_15.setScaledContents(True)
        self.online_clients_area.setWidget(self.scrollAreaWidgetContents_3)
        self.label_15.raise_()
        self.online_clients_label.raise_()
        self.online_clients_close_button.raise_()
        self.online_clients_list.raise_()
        self.label_14.raise_()
        self.file_send_button = QPushButton(self.centralwidget)
        self.file_send_button.setObjectName(u"file_send_button")
        self.file_send_button.setGeometry(QRect(410, 380, 61, 41))
        self.file_send_button.setStyleSheet(u"border-radius: 8px;\n"
"border: 1px solid #e0e4e7;\n"
"padding: 5px 15px;\n"
"color: #FFFFFF;\n"
"background-color: #7B68EE;")
        icon6 = QIcon()
        icon6.addFile(u":/icons/Icons/folder.png", QSize(), QIcon.Normal, QIcon.Off)
        self.file_send_button.setIcon(icon6)
        self.file_send_button.setIconSize(QSize(30, 30))
        self.download_file_area = QScrollArea(self.centralwidget)
        self.download_file_area.setObjectName(u"download_file_area")
        self.download_file_area.setGeometry(QRect(140, 110, 295, 210))
        self.download_file_area.setStyleSheet(u"border-radius: 8px;\n"
"border: 1px solid #e0e4e7;\n"
"color: #FFFFFF")
        self.download_file_area.setWidgetResizable(True)
        self.scrollAreaWidgetContents_4 = QWidget()
        self.scrollAreaWidgetContents_4.setObjectName(u"scrollAreaWidgetContents_4")
        self.scrollAreaWidgetContents_4.setGeometry(QRect(0, 0, 293, 208))
        self.file_info = QLabel(self.scrollAreaWidgetContents_4)
        self.file_info.setObjectName(u"file_info")
        self.file_info.setGeometry(QRect(10, 60, 270, 90))
        self.file_info.setFont(font)
        self.file_info.setStyleSheet(u"border-radius: 8px;\n"
"border: 1px solid #e0e4e7;\n"
"padding: 5px 5px;\n"
"color: #FFFFFF;\n"
"background-color: #6A5ACD;")
        self.download_button = QPushButton(self.scrollAreaWidgetContents_4)
        self.download_button.setObjectName(u"download_button")
        self.download_button.setGeometry(QRect(10, 160, 71, 31))
        self.download_button.setFont(font)
        self.download_button.setStyleSheet(u"border-radius: 8px;\n"
"border: 1px solid #e0e4e7;\n"
"color: #FFFFFF;\n"
"background-color: #2E8B57;")
        self.cancel_download_button = QPushButton(self.scrollAreaWidgetContents_4)
        self.cancel_download_button.setObjectName(u"cancel_download_button")
        self.cancel_download_button.setGeometry(QRect(210, 160, 71, 31))
        self.cancel_download_button.setFont(font)
        self.cancel_download_button.setStyleSheet(u"border-radius: 8px;\n"
"border: 1px solid #e0e4e7;\n"
"color: #FFFFFF;\n"
"background-color: #B22222;")
        self.dowload_title = QLabel(self.scrollAreaWidgetContents_4)
        self.dowload_title.setObjectName(u"dowload_title")
        self.dowload_title.setGeometry(QRect(20, 10, 251, 41))
        font2 = QFont()
        font2.setFamilies([u"Roboto Mono"])
        font2.setPointSize(22)
        self.dowload_title.setFont(font2)
        self.dowload_title.setStyleSheet(u"text-align: center;")
        self.rocket_icon = QLabel(self.scrollAreaWidgetContents_4)
        self.rocket_icon.setObjectName(u"rocket_icon")
        self.rocket_icon.setGeometry(QRect(0, 50, 41, 41))
        self.rocket_icon.setStyleSheet(u"background-color: transparent;\n"
"border: 0px;")
        self.rocket_icon.setPixmap(QPixmap(u":/icons/Icons/rocket.png"))
        self.rocket_icon.setScaledContents(True)
        self.ufo_icon = QLabel(self.scrollAreaWidgetContents_4)
        self.ufo_icon.setObjectName(u"ufo_icon")
        self.ufo_icon.setGeometry(QRect(220, -10, 41, 41))
        self.ufo_icon.setStyleSheet(u"background-color: transparent;\n"
"border: 0px;")
        self.ufo_icon.setPixmap(QPixmap(u":/icons/Icons/ufo.png"))
        self.ufo_icon.setScaledContents(True)
        self.download_file_area.setWidget(self.scrollAreaWidgetContents_4)
        self.label_3 = QLabel(self.centralwidget)
        self.label_3.setObjectName(u"label_3")
        self.label_3.setGeometry(QRect(0, 0, 550, 440))
        self.label_3.setPixmap(QPixmap(u":/images/Icons/5471985.jpg"))
        self.label_3.setScaledContents(True)
        self.label_2 = QLabel(self.centralwidget)
        self.label_2.setObjectName(u"label_2")
        self.label_2.setGeometry(QRect(500, 30, 41, 41))
        self.label_2.setStyleSheet(u"background-color: transparent;")
        self.label_2.setPixmap(QPixmap(u":/icons/Icons/meteor.png"))
        self.label_2.setScaledContents(True)
        self.label_4 = QLabel(self.centralwidget)
        self.label_4.setObjectName(u"label_4")
        self.label_4.setGeometry(QRect(310, 400, 31, 41))
        self.label_4.setStyleSheet(u"background-color: transparent")
        self.label_4.setPixmap(QPixmap(u":/icons/Icons/black-hole.png"))
        self.label_4.setScaledContents(True)
        self.label_5 = QLabel(self.centralwidget)
        self.label_5.setObjectName(u"label_5")
        self.label_5.setGeometry(QRect(400, -30, 71, 71))
        self.label_5.setStyleSheet(u"background-color: transparent;")
        self.label_5.setPixmap(QPixmap(u":/icons/Icons/solar-system.png"))
        self.label_5.setScaledContents(True)
        self.label_9 = QLabel(self.centralwidget)
        self.label_9.setObjectName(u"label_9")
        self.label_9.setGeometry(QRect(0, 330, 41, 41))
        self.label_9.setStyleSheet(u"background-color: transparent;\n"
"border: 0px;")
        self.label_9.setPixmap(QPixmap(u":/icons/Icons/astronaut (1).png"))
        self.label_9.setScaledContents(True)
        self.label_13 = QLabel(self.centralwidget)
        self.label_13.setObjectName(u"label_13")
        self.label_13.setGeometry(QRect(330, 10, 211, 21))
        self.label_13.setFont(font)
        self.label_13.setStyleSheet(u"background-color: transparent;")
        MainWindow.setCentralWidget(self.centralwidget)
        self.label_3.raise_()
        self.chat_input.raise_()
        self.chat_viewer.raise_()
        self.emoji_area.raise_()
        self.send_button.raise_()
        self.emoji_open_button.raise_()
        self.menu_open_button.raise_()
        self.file_send_button.raise_()
        self.online_clients_area.raise_()
        self.download_file_area.raise_()
        self.label_2.raise_()
        self.label_4.raise_()
        self.label_5.raise_()
        self.label_9.raise_()
        self.menu_area.raise_()
        self.label_13.raise_()

        self.retranslateUi(MainWindow)

        QMetaObject.connectSlotsByName(MainWindow)
    # setupUi

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QCoreApplication.translate("MainWindow", u"SimpleChat", None))
        self.chat_input.setHtml(QCoreApplication.translate("MainWindow", u"<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><meta charset=\"utf-8\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"hr { height: 1px; border-width: 0; }\n"
"li.unchecked::marker { content: \"\\2610\"; }\n"
"li.checked::marker { content: \"\\2612\"; }\n"
"</style></head><body style=\" font-family:'Roboto Mono'; font-size:10pt; font-weight:400; font-style:normal;\">\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-family:'Segoe UI'; font-size:9pt;\"><br /></p></body></html>", None))
        self.chat_input.setPlaceholderText(QCoreApplication.translate("MainWindow", u"Enter your Message", None))
        self.send_button.setText("")
        self.emoji_1.setText(QCoreApplication.translate("MainWindow", u":grinning_face_with_big_eyes:", None))
        self.emoji_close_button.setText(QCoreApplication.translate("MainWindow", u"X", None))
        self.emoji_2.setText(QCoreApplication.translate("MainWindow", u":grinning_face_with_smiling_eyes:", None))
        self.emoji_3.setText(QCoreApplication.translate("MainWindow", u":grimacing_face:", None))
        self.emoji_4.setText(QCoreApplication.translate("MainWindow", u":grinning_face_with_sweat:", None))
        self.emoji_5.setText(QCoreApplication.translate("MainWindow", u":grinning_squinting_face:", None))
        self.emoji_6.setText(QCoreApplication.translate("MainWindow", u":angry_face:", None))
        self.emoji_7.setText(QCoreApplication.translate("MainWindow", u":astonished_face:", None))
        self.emoji_8.setText(QCoreApplication.translate("MainWindow", u":beaming_face_with_smiling_eyes:", None))
        self.emoji_9.setText(QCoreApplication.translate("MainWindow", u":clown_face:", None))
        self.emoji_14.setText(QCoreApplication.translate("MainWindow", u":disappointed_face:", None))
        self.emoji_10.setText(QCoreApplication.translate("MainWindow", u":cold_face:", None))
        self.emoji_17.setText(QCoreApplication.translate("MainWindow", u":expressionless_face:", None))
        self.emoji_13.setText(QCoreApplication.translate("MainWindow", u":crying_face:", None))
        self.emoji_18.setText(QCoreApplication.translate("MainWindow", u":face_blowing_a_kiss:", None))
        self.emoji_11.setText(QCoreApplication.translate("MainWindow", u":confused_face:", None))
        self.emoji_15.setText(QCoreApplication.translate("MainWindow", u":drooling_face:", None))
        self.emoji_12.setText(QCoreApplication.translate("MainWindow", u":cowboy_hat_face:", None))
        self.emoji_16.setText(QCoreApplication.translate("MainWindow", u":enraged_face:", None))
        self.emoji_23.setText(QCoreApplication.translate("MainWindow", u":face_screaming_in_fear:", None))
        self.emoji_19.setText(QCoreApplication.translate("MainWindow", u":face_exhaling:", None))
        self.emoji_26.setText(QCoreApplication.translate("MainWindow", u":face_with_diagonal_mouth:", None))
        self.emoji_22.setText(QCoreApplication.translate("MainWindow", u":face_savoring_food:", None))
        self.emoji_27.setText(QCoreApplication.translate("MainWindow", u":face_with_head-bandage:", None))
        self.emoji_20.setText(QCoreApplication.translate("MainWindow", u":face_holding_back_tears:", None))
        self.emoji_24.setText(QCoreApplication.translate("MainWindow", u":face_vomiting:", None))
        self.emoji_21.setText(QCoreApplication.translate("MainWindow", u":face_in_clouds:", None))
        self.emoji_25.setText(QCoreApplication.translate("MainWindow", u":face_with_crossed-out_eyes:", None))
        self.emoji_32.setText(QCoreApplication.translate("MainWindow", u":face_with_tears_of_joy:", None))
        self.emoji_28.setText(QCoreApplication.translate("MainWindow", u":face_with_medical_mask:", None))
        self.emoji_35.setText(QCoreApplication.translate("MainWindow", u":flushed_face:", None))
        self.emoji_31.setText(QCoreApplication.translate("MainWindow", u":face_with_symbols_on_mouth:", None))
        self.emoji_36.setText(QCoreApplication.translate("MainWindow", u":frowning_face_with_open_mouth:", None))
        self.emoji_29.setText(QCoreApplication.translate("MainWindow", u":face_with_raised_eyebrow:", None))
        self.emoji_33.setText(QCoreApplication.translate("MainWindow", u":face_with_tongue:", None))
        self.emoji_30.setText(QCoreApplication.translate("MainWindow", u":face_with_rolling_eyes:", None))
        self.emoji_34.setText(QCoreApplication.translate("MainWindow", u":face_without_mouth:", None))
        self.emoji_41.setText(QCoreApplication.translate("MainWindow", u":kiss_mark:", None))
        self.emoji_37.setText(QCoreApplication.translate("MainWindow", u":frog:", None))
        self.emoji_44.setText(QCoreApplication.translate("MainWindow", u":raised_fist_dark_skin_tone:", None))
        self.emoji_40.setText(QCoreApplication.translate("MainWindow", u":index_pointing_up:", None))
        self.emoji_45.setText(QCoreApplication.translate("MainWindow", u":see-no-evil_monkey:", None))
        self.emoji_38.setText(QCoreApplication.translate("MainWindow", u":grinning_cat_with_smiling_eyes:", None))
        self.emoji_42.setText(QCoreApplication.translate("MainWindow", u":kiwi_fruit:", None))
        self.emoji_39.setText(QCoreApplication.translate("MainWindow", u":handshake:", None))
        self.emoji_43.setText(QCoreApplication.translate("MainWindow", u":lobster:", None))
        self.base_icon.setText("")
        self.scope_icon.setText("")
        self.emoji_open_button.setText("")
        self.menu_close_button.setText(QCoreApplication.translate("MainWindow", u"Menu", None))
        self.online_clients_open_button.setText(QCoreApplication.translate("MainWindow", u"Users", None))
        self.label.setText("")
        self.label_6.setText("")
        self.label_7.setText("")
        self.label_8.setText("")
        self.label_10.setText("")
        self.label_11.setText("")
        self.label_12.setText("")
        self.menu_open_button.setText(QCoreApplication.translate("MainWindow", u"Menu", None))
        self.online_clients_label.setText(QCoreApplication.translate("MainWindow", u"Online", None))
        self.online_clients_close_button.setText(QCoreApplication.translate("MainWindow", u"X", None))
        self.label_14.setText("")
        self.label_15.setText("")
        self.file_send_button.setText("")
        self.file_info.setText(QCoreApplication.translate("MainWindow", u"File Info", None))
        self.download_button.setText(QCoreApplication.translate("MainWindow", u"Download", None))
        self.cancel_download_button.setText(QCoreApplication.translate("MainWindow", u"Cancel", None))
        self.dowload_title.setText(QCoreApplication.translate("MainWindow", u"Download File", None))
        self.rocket_icon.setText("")
        self.ufo_icon.setText("")
        self.label_3.setText("")
        self.label_2.setText("")
        self.label_4.setText("")
        self.label_5.setText("")
        self.label_9.setText("")
        self.label_13.setText(QCoreApplication.translate("MainWindow", u"\u0421\u0442\u0443\u0434\u0435\u043d\u0442 \u041e\u0406-12 \u041c\u0430\u043c\u0440\u0430\u043a \u0410\u0440\u0442\u0435\u043c", None))
    # retranslateUi

